## PyTorch 基础 : 张量
在第一章中我们已经通过官方的入门教程对PyTorch有了一定的了解，这一章会详细介绍PyTorch 里面的基础知识。 全部掌握了这些基础知识，在后面的应用中才能更加快速进阶，如果你已经对PyTorch有一定的了解，可以跳过此章

In [2]:
# 首先要引入相关的包
import torch
import numpy as np
#打印一下版本
torch.__version__

'1.3.1+cpu'

## 张量(Tensor)
张量的英文是Tensor，它是PyTorch里面基础的运算单位，与Numpy的ndarray相同都表示的是一个多维的矩阵。 与ndarray的最大区别就是，PyTorch的Tensor可以在 GPU 上运行，而 numpy 的 ndarray 只能在 CPU 上运行，在GPU上运行大大加快了运算速度。

下面我们生成一个简单的张量

In [3]:
x = torch.rand(2, 3)
x

tensor([[0.7891, 0.1291, 0.0209],
        [0.5059, 0.3572, 0.6630]])

In [4]:
# 可以使用与numpy相同的shape属性查看
print(x.shape)
# 也可以使用size()函数，返回的结果都是相同的
print(x.size())

torch.Size([2, 3])
torch.Size([2, 3])


张量（Tensor）是一个定义在一些向量空间和一些对偶空间的笛卡儿积上的多重线性映射，其坐标是|n|维空间内，有|n|个分量的一种量， 其中每个分量都是坐标的函数， 而在坐标变换时，这些分量也依照某些规则作线性变换。r称为该张量的秩或阶（与矩阵的秩和阶均无关系）。 (来自百度百科)

下面我们来生成一些多维的张量：

In [5]:
y=torch.rand(2,3,4,5)
print(y.size())
y

torch.Size([2, 3, 4, 5])


tensor([[[[0.4933, 0.4670, 0.2380, 0.3979, 0.3324],
          [0.8107, 0.9451, 0.4332, 0.5548, 0.1706],
          [0.8978, 0.8064, 0.3237, 0.1923, 0.7306],
          [0.3488, 0.9177, 0.1956, 0.3568, 0.2774]],

         [[0.5584, 0.4556, 0.2757, 0.5569, 0.9439],
          [0.1413, 0.3756, 0.9902, 0.4945, 0.1590],
          [0.9931, 0.4175, 0.5061, 0.2508, 0.2069],
          [0.7108, 0.9539, 0.5618, 0.3750, 0.6643]],

         [[0.0252, 0.9048, 0.2148, 0.9651, 0.2656],
          [0.9825, 0.8798, 0.2003, 0.8898, 0.3835],
          [0.7906, 0.4456, 0.8944, 0.3222, 0.4181],
          [0.9358, 0.2632, 0.9220, 0.5272, 0.0519]]],


        [[[0.0900, 0.1233, 0.8008, 0.0293, 0.8697],
          [0.0525, 0.2862, 0.2545, 0.6230, 0.7471],
          [0.2725, 0.7773, 0.4117, 0.9383, 0.0889],
          [0.8540, 0.1452, 0.9763, 0.8564, 0.9221]],

         [[0.6901, 0.0521, 0.7369, 0.0249, 0.9547],
          [0.7436, 0.7347, 0.7196, 0.1457, 0.3268],
          [0.4330, 0.9334, 0.9458, 0.1418, 0.7683],
  

在同构的意义下，第零阶张量 （r = 0） 为标量 （Scalar），第一阶张量 （r = 1） 为向量 （Vector）， 第二阶张量 （r = 2） 则成为矩阵 （Matrix），第三阶以上的统称为多维张量。

其中要特别注意的就是标量，我们先生成一个标量：

In [9]:
#我们直接使用现有数字生成
scalar =torch.tensor(3.1433223)
print(scalar)
#打印标量的大小
scalar.size()

tensor(3.1433)


torch.Size([])

特别的：如果张量中只有一个元素的tensor也可以调用tensor.item方法

In [10]:
tensor = torch.tensor([3.1433223]) 
print(tensor)
tensor.size()

tensor([3.1433])


torch.Size([1])

In [11]:
tensor.item()

3.143322229385376

## 基本类型
Tensor的基本数据类型有五种：

- 32位浮点型：torch.FloatTensor。 (默认)
- 64位整型：torch.LongTensor。
- 32位整型：torch.IntTensor。
- 16位整型：torch.ShortTensor。
- 64位浮点型：torch.DoubleTensor。
除以上数字类型外，还有 byte和chart型

In [13]:
long=tensor.long()
long

tensor([3])

In [14]:
half=tensor.half()
half

tensor([3.1426], dtype=torch.float16)

In [15]:
int_t=tensor.int()
int_t

tensor([3], dtype=torch.int32)

In [16]:
flo = tensor.float()
flo

tensor([3.1433])

In [17]:
short = tensor.short()
short


tensor([3], dtype=torch.int16)

In [18]:
ch = tensor.char()
ch

tensor([3], dtype=torch.int8)

In [19]:
bt = tensor.byte()
bt

tensor([3], dtype=torch.uint8)

## Numpy转换
使用numpy方法将Tensor转为ndarray

In [20]:
a = torch.randn((3, 2))
# tensor转化为numpy
numpy_a = a.numpy()
print(numpy_a)

[[ 0.994366    0.39849254]
 [-0.8563921  -0.55437636]
 [-1.4639996   0.5079527 ]]


numpy转化为Tensor

In [21]:
torch_a = torch.from_numpy(numpy_a)
torch_a

tensor([[ 0.9944,  0.3985],
        [-0.8564, -0.5544],
        [-1.4640,  0.5080]])

**Tensor和numpy对象共享内存，所以他们之间的转换很快，而且几乎不会消耗什么资源。但这也意味着，如果其中一个变了，另外一个也会随之改变。**

## 设备间转换
一般情况下可以使用.cuda方法将tensor移动到gpu，这步操作需要cuda设备支持

In [22]:
cpu_a=torch.rand(4, 3)
cpu_a.type()

'torch.FloatTensor'

In [24]:
gpu_a=cpu_a.cuda()
gpu_a.type()

AssertionError: Torch not compiled with CUDA enabled

In [25]:
cpu_b=gpu_a.cpu()
cpu_b.type()

NameError: name 'gpu_a' is not defined

In [26]:
#使用torch.cuda.is_available()来确定是否有cuda设备
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(device)
#将tensor传送到设备
gpu_b=cpu_b.to(device)
gpu_b.type()

cpu


NameError: name 'cpu_b' is not defined

## 初始化
Pytorch中有许多默认的初始化方法可以使用

In [27]:
# 使用[0,1]均匀分布随机初始化二维数组
rnd = torch.rand(5, 3)
rnd

tensor([[0.3640, 0.8064, 0.3318],
        [0.0847, 0.6637, 0.3480],
        [0.1453, 0.3390, 0.5043],
        [0.3631, 0.5999, 0.9964],
        [0.2400, 0.1982, 0.7311]])

In [28]:
##初始化，使用1填充
one = torch.ones(2, 2)
one

tensor([[1., 1.],
        [1., 1.]])

In [29]:
##初始化，使用0填充
zero=torch.zeros(2,2)
zero

tensor([[0., 0.],
        [0., 0.]])

In [30]:
#初始化一个单位矩阵，即对角线为1 其他为0
eye=torch.eye(2,2)
eye

tensor([[1., 0.],
        [0., 1.]])

常用方法
PyTorch中对张量的操作api 和 NumPy 非常相似，如果熟悉 NumPy 中的操作，那么他们二者基本是一致的：

In [31]:
x = torch.randn(3, 3)
print(x)

tensor([[-0.6925,  2.1848,  0.7643],
        [-0.1136, -0.8792, -0.1225],
        [ 0.4595, -0.3276, -1.2225]])


In [32]:
# 沿着行取最大值
max_value, max_idx = torch.max(x, dim=1)
print(max_value, max_idx)

tensor([ 2.1848, -0.1136,  0.4595]) tensor([1, 0, 0])


In [33]:
# 每行 x 求和
sum_x = torch.sum(x, dim=1)
print(sum_x)

tensor([ 2.2566, -1.1153, -1.0905])


In [34]:
y=torch.randn(3, 3)
z = x + y
print(z)

tensor([[ 1.2020,  2.4203,  3.2568],
        [-0.9682, -1.3551, -0.8004],
        [ 0.9599, -0.3119, -1.0414]])


In [35]:
# add 完成后x的值改变了
x.add_(y)
print(x)

tensor([[ 1.2020,  2.4203,  3.2568],
        [-0.9682, -1.3551, -0.8004],
        [ 0.9599, -0.3119, -1.0414]])
