## PyTorch是什么?
基于Python的科学计算包，服务于以下两种场景:
- 作为NumPy的替代品，可以使用GPU的强大计算能力
- 提供最大的灵活性和高速的深度学习研究平台

## 开始
Tensors（张量）
Tensors与Numpy中的 ndarrays类似，但是在PyTorch中 Tensors 可以使用GPU进行计算.


In [1]:
from __future__ import print_function
import torch

In [2]:
# 创建一个 5x3 矩阵, 但是未初始化:
x = torch.empty(5, 3)
print(x)

tensor([[8.4490e-39, 1.0194e-38, 9.0919e-39],
        [8.4490e-39, 1.0102e-38, 1.0378e-38],
        [8.9082e-39, 1.0653e-38, 1.1204e-38],
        [9.1837e-39, 9.1837e-39, 1.0102e-38],
        [1.0010e-38, 9.0919e-39, 3.8572e-39]])


In [3]:
# 创建一个随机初始化的矩阵:
x = torch.rand(5,3)
print(x)

tensor([[0.5540, 0.3917, 0.1597],
        [0.3463, 0.3722, 0.1491],
        [0.2113, 0.2262, 0.9749],
        [0.0374, 0.6723, 0.3190],
        [0.0461, 0.4829, 0.4378]])


In [4]:
# 创建一个0填充的矩阵，数据类型为long:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [5]:
# 创建tensor并使用现有数据初始化:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


In [6]:
# 根据现有的张量创建张量。 这些方法将重用输入张量的属性，例如， dtype，除非设置新的值进行覆盖
x = x.new_ones(5, 3, dtype=torch.double)      # new_* 方法来创建对象
print(x)

x = torch.randn_like(x, dtype=torch.float)    # 覆盖 dtype!
print(x)                                      #  对象的size 是相同的，只是值和类型发生了变化

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[ 0.4597, -0.7631, -0.7974],
        [ 1.0852,  1.6549,  1.3833],
        [-1.0959,  0.1917, -0.4401],
        [-1.5341, -0.1622, -0.8012],
        [ 0.3161, -0.7231,  0.8081]])


In [7]:
print(x.size())

torch.Size([5, 3])


In [8]:
# 加法1
y = torch.rand(5, 3)
print(x + y)

tensor([[ 1.0465, -0.1595, -0.7063],
        [ 1.7233,  1.9144,  1.5306],
        [-0.8898,  0.5529,  0.1649],
        [-0.6677,  0.6142, -0.7528],
        [ 0.8993, -0.1602,  1.7276]])


In [9]:
# 加法2
print(torch.add(x, y))

tensor([[ 1.0465, -0.1595, -0.7063],
        [ 1.7233,  1.9144,  1.5306],
        [-0.8898,  0.5529,  0.1649],
        [-0.6677,  0.6142, -0.7528],
        [ 0.8993, -0.1602,  1.7276]])


In [10]:
# 提供输出tensor作为参数
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[ 1.0465, -0.1595, -0.7063],
        [ 1.7233,  1.9144,  1.5306],
        [-0.8898,  0.5529,  0.1649],
        [-0.6677,  0.6142, -0.7528],
        [ 0.8993, -0.1602,  1.7276]])


In [11]:
# 替换
# adds x to y
y.add_(x)
print(y)

tensor([[ 1.0465, -0.1595, -0.7063],
        [ 1.7233,  1.9144,  1.5306],
        [-0.8898,  0.5529,  0.1649],
        [-0.6677,  0.6142, -0.7528],
        [ 0.8993, -0.1602,  1.7276]])


## 任何 以``_`` 结尾的操作都会用结果替换原变量. 例如: ``x.copy_(y)``, ``x.t_()``, 都会改变 ``x``.

In [13]:
# 你可以使用与NumPy索引方式相同的操作来进行对张量的操作
print(x[:, 1])

tensor([-0.7631,  1.6549,  0.1917, -0.1622, -0.7231])


## torch.view: 可以改变张量的维度和大小

译者注：torch.view 与Numpy的reshape类似

In [14]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  #  size -1 从其他维度推断
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


如果你有只有一个元素的张量，使用.item()来得到Python数据类型的数值

In [16]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([2.6548])
2.6548404693603516


## NumPy 转换
将一个Torch Tensor转换为NumPy数组是一件轻松的事，反之亦然。

Torch Tensor与NumPy数组共享底层内存地址，修改一个会导致另一个的变化。

将一个Torch Tensor转换为NumPy数组

In [17]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [18]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


In [19]:
#  观察numpy数组的值是如何改变的。
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


NumPy Array 转化成 Torch Tensor

使用from_numpy自动转化

In [20]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


## CUDA 张量
使用.to 方法 可以将Tensor移动到任何设备中

In [21]:
# is_available 函数判断是否有cuda可以使用
# ``torch.device``将张量移动到指定的设备中
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA 设备对象
    y = torch.ones_like(x, device=device)  # 直接从GPU创建张量
    x = x.to(device)                       # 或者直接使用``.to("cuda")``将张量移动到cuda中
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` 也会对变量的类型做更改