## PyTorch是什么?
基于Python的科学计算包，服务于以下两种场景:
- 作为NumPy的替代品，可以使用GPU的强大计算能力
- 提供最大的灵活性和高速的深度学习研究平台

## 开始
Tensors（张量）
Tensors与Numpy中的 ndarrays类似，但是在PyTorch中 Tensors 可以使用GPU进行计算.


In [1]:
from __future__ import print_function
import torch

In [2]:
# 创建一个 5x3 矩阵, 但是未初始化:
x = torch.empty(5, 3)
print(x)

tensor([[-2.7264e+38,  4.5552e-41,  3.0592e-36],
        [ 0.0000e+00, -8.4027e-35,  8.0915e-04],
        [ 2.8444e+23,  4.5552e-41,  1.4434e-38],
        [ 0.0000e+00, -1.1490e-11, -4.3795e+29],
        [ 2.8444e+23,  4.5552e-41,  1.4434e-38]])


In [3]:
# 创建一个随机初始化的矩阵:
x = torch.rand(5,3)
print(x)

tensor([[0.5006, 0.6957, 0.2568],
        [0.7249, 0.1810, 0.4312],
        [0.3644, 0.3444, 0.7412],
        [0.9773, 0.6550, 0.0551],
        [0.1577, 0.8947, 0.6228]])


In [4]:
# 创建一个0填充的矩阵，数据类型为long:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [5]:
# 创建tensor并使用现有数据初始化:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


In [6]:
# 根据现有的张量创建张量。 这些方法将重用输入张量的属性，例如， dtype，除非设置新的值进行覆盖
x = x.new_ones(5, 3, dtype=torch.double)      # new_* 方法来创建对象
print(x)

x = torch.randn_like(x, dtype=torch.float)    # 覆盖 dtype!
print(x)                                      #  对象的size 是相同的，只是值和类型发生了变化

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[-1.2906,  0.3489,  0.1963],
        [ 0.2237,  1.7810, -0.3885],
        [-0.1828,  1.2985,  0.1497],
        [-0.6891, -0.1615, -1.2190],
        [-0.9776,  1.2575, -1.8439]])


In [7]:
print(x.size())

torch.Size([5, 3])


In [8]:
# 加法1
y = torch.rand(5, 3)
print(x + y)

tensor([[-0.9562,  0.8720,  0.7987],
        [ 0.6783,  1.9567, -0.2696],
        [ 0.5490,  1.3642,  1.0403],
        [-0.3733,  0.6846, -0.3005],
        [-0.4397,  1.7300, -1.4436]])


In [9]:
# 加法2
print(torch.add(x, y))

tensor([[-0.9562,  0.8720,  0.7987],
        [ 0.6783,  1.9567, -0.2696],
        [ 0.5490,  1.3642,  1.0403],
        [-0.3733,  0.6846, -0.3005],
        [-0.4397,  1.7300, -1.4436]])


In [10]:
# 提供输出tensor作为参数
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[-0.9562,  0.8720,  0.7987],
        [ 0.6783,  1.9567, -0.2696],
        [ 0.5490,  1.3642,  1.0403],
        [-0.3733,  0.6846, -0.3005],
        [-0.4397,  1.7300, -1.4436]])


In [11]:
# 替换
# adds x to y
y.add_(x)
print(y)

tensor([[-0.9562,  0.8720,  0.7987],
        [ 0.6783,  1.9567, -0.2696],
        [ 0.5490,  1.3642,  1.0403],
        [-0.3733,  0.6846, -0.3005],
        [-0.4397,  1.7300, -1.4436]])


## 任何 以``_`` 结尾的操作都会用结果替换原变量. 例如: ``x.copy_(y)``, ``x.t_()``, 都会改变 ``x``.

In [12]:
# 你可以使用与NumPy索引方式相同的操作来进行对张量的操作
print(x[:, 1])

tensor([ 0.3489,  1.7810,  1.2985, -0.1615,  1.2575])


## torch.view: 可以改变张量的维度和大小

译者注：torch.view 与Numpy的reshape类似

In [13]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  #  size -1 从其他维度推断
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


如果你有只有一个元素的张量，使用.item()来得到Python数据类型的数值

In [14]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([-0.4704])
-0.470426470041275


## NumPy 转换
将一个Torch Tensor转换为NumPy数组是一件轻松的事，反之亦然。

Torch Tensor与NumPy数组共享底层内存地址，修改一个会导致另一个的变化。

将一个Torch Tensor转换为NumPy数组

In [15]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [16]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


In [17]:
#  观察numpy数组的值是如何改变的。
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


NumPy Array 转化成 Torch Tensor

使用from_numpy自动转化

In [18]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


## CUDA 张量
使用.to 方法 可以将Tensor移动到任何设备中

In [19]:
# is_available 函数判断是否有cuda可以使用
# ``torch.device``将张量移动到指定的设备中
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA 设备对象
    y = torch.ones_like(x, device=device)  # 直接从GPU创建张量
    x = x.to(device)                       # 或者直接使用``.to("cuda")``将张量移动到cuda中
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` 也会对变量的类型做更改

tensor([0.5296], device='cuda:0')
tensor([0.5296], dtype=torch.float64)
